import type { AirlineProfile, AirportProfile, PeakTravelWindow } from "@/types/airport";

export const peakTravelWindows: PeakTravelWindow[] = [
  {
    level: "extreme",
    multiplier: 1.5,
    name: "Thanksgiving return rush",
    dates: ["2026-11-25", "2026-11-29"],
  },
  {
    level: "extreme",
    multiplier: 1.5,
    name: "Christmas peak",
    dates: ["2026-12-18", "2026-12-19", "2026-12-20", "2026-12-21", "2026-12-26", "2026-12-27", "2026-12-28", "2026-12-29"],
  },
  {
    level: "high",
    multiplier: 1.35,
    name: "Holiday weekend pressure",
    dates: ["2026-05-22", "2026-05-25", "2026-07-02", "2026-07-05", "2026-09-04", "2026-09-07"],
  },
];

export const airportProfiles: Record<string, AirportProfile> = {
  JFK: {
    code: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    constructionBufferMinutes: { baseline: 15, peak: 30 },
    standardBoardingBuffer: { domestic: 30, international: 45 },
    defaultPostSecurityBuffer: 40,
    bagCutoffs: {
      checkedDomestic: 60,
      checkedInternational: 60,
      carryOnDomestic: 30,
      carryOnInternational: 60,
    },
    weatherStation: { lat: 40.6413, lon: -73.7781 },
    alerts: [
      "Major roadway construction through 2030 can add terminal access delay.",
      "Terminal 4 uses Van Wyck access; Terminal 8 uses JFK Expressway access.",
    ],
    terminals: [
      {
        id: "1",
        name: "Terminal 1",
        airportCode: "JFK",
        airlines: ["AF", "LH", "KE", "TK", "LX", "TP"],
        curbToSecurityMinutes: [5, 7],
        securityToGateMinutes: [5, 10],
        peakWindows: ["5:00am-8:00am", "6:00pm-10:00pm"],
        notes: ["Under major renovation.", "International banks can spike security fast."],
        security: {
          waitEstimate: { offPeak: 20, normal: 30, peak: 45, holiday: 60 },
          services: { standard: true, precheck: true },
          serviceHours: {
            precheck: { opensAt: "04:00", closesAt: "20:00" },
          },
          notes: ["No CLEAR."],
        },
      },
      {
        id: "4",
        name: "Terminal 4",
        airportCode: "JFK",
        airlines: ["DL", "KL", "VS", "LA", "AM", "EK", "EY", "SQ"],
        curbToSecurityMinutes: [7, 10],
        securityToGateMinutes: [5, 15],
        peakWindows: ["5:00am-8:00am", "4:00pm-7:00pm"],
        notes: ["Largest terminal.", "T4 RESERVE and Touchless ID can materially cut security time."],
        accessNotes: ["Use Van Wyck access.", "Remote rideshare pickup lot operates 12pm-2am."],
        security: {
          waitEstimate: { offPeak: 25, normal: 35, peak: 50, holiday: 65 },
          services: { standard: true, precheck: true, clear: true, reserve: true, "touchless-id": true },
          serviceHours: {
            precheck: { opensAt: "04:00", closesAt: "20:00" },
            clear: { opensAt: "04:30", closesAt: "22:00" },
            reserve: { opensAt: "04:00", closesAt: "22:00", note: "Bookable up to 72 hours before departure." },
            "touchless-id": { opensAt: "04:00", closesAt: "20:00" },
          },
          notes: ["Arrivals-level security can be shorter but lacks CLEAR."],
        },
      },
      {
        id: "5",
        name: "Terminal 5",
        airportCode: "JFK",
        airlines: ["B6"],
        curbToSecurityMinutes: [5, 5],
        securityToGateMinutes: [5, 10],
        peakWindows: ["6:00am-9:00am"],
        notes: ["Efficient, compact terminal."],
        accessNotes: ["Updated roadway pattern since October 2025."],
        security: {
          waitEstimate: { offPeak: 15, normal: 20, peak: 30, holiday: 45 },
          services: { standard: true, precheck: true },
          serviceHours: {
            precheck: { opensAt: "06:00", closesAt: "19:30", note: "Can close early." },
          },
          notes: ["No CLEAR."],
        },
      },
      {
        id: "7",
        name: "Terminal 7",
        airportCode: "JFK",
        airlines: ["EI", "AC", "FI", "F9", "ET", "LO", "DE", "NH"],
        curbToSecurityMinutes: [3, 5],
        securityToGateMinutes: [1, 2],
        peakWindows: ["5:00am-8:00am"],
        notes: ["Compact terminal.", "CLEAR kiosks present but currently closed."],
        accessNotes: ["Updated roadway pattern since October 2025."],
        security: {
          waitEstimate: { offPeak: 15, normal: 20, peak: 30, holiday: 40 },
          services: { standard: true, precheck: true },
          serviceHours: {
            precheck: { opensAt: "04:00", closesAt: "19:00" },
          },
          notes: ["CLEAR closed."],
        },
      },
      {
        id: "8",
        name: "Terminal 8",
        airportCode: "JFK",
        airlines: ["AA", "BA", "IB", "JL", "QF", "QR", "AS", "HA"],
        curbToSecurityMinutes: [5, 8],
        securityToGateMinutes: [5, 15],
        peakWindows: ["5:00am-8:00am", "4:00pm-7:00pm"],
        notes: ["Concourse C tunnel adds 10-15 minutes."],
        accessNotes: ["Use JFK Expressway access."],
        security: {
          waitEstimate: { offPeak: 20, normal: 30, peak: 45, holiday: 60 },
          services: { standard: true, precheck: true, "touchless-id": true },
          serviceHours: {
            precheck: { opensAt: "03:30", closesAt: "22:00" },
            "touchless-id": { opensAt: "04:00", closesAt: "20:00" },
          },
          notes: ["No CLEAR."],
        },
      },
    ],
  },
  LGA: {
    code: "LGA",
    name: "LaGuardia Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    constructionBufferMinutes: { baseline: 8, peak: 15 },
    standardBoardingBuffer: { domestic: 30, international: 40 },
    defaultPostSecurityBuffer: 35,
    bagCutoffs: { checkedDomestic: 45, checkedInternational: 60, carryOnDomestic: 30, carryOnInternational: 45 },
    weatherStation: { lat: 40.7769, lon: -73.8740 },
    alerts: ["Roadway congestion is common during weekday mornings."],
    terminals: [
      {
        id: "A",
        name: "Terminal A",
        airportCode: "LGA",
        airlines: ["F9", "NK", "B6"],
        curbToSecurityMinutes: [4, 6],
        securityToGateMinutes: [4, 8],
        peakWindows: ["6:00am-9:00am"],
        notes: ["Smaller footprint."],
        security: {
          waitEstimate: { offPeak: 12, normal: 20, peak: 30, holiday: 40 },
          services: { standard: true, precheck: true },
          notes: [],
        },
      },
      {
        id: "B",
        name: "Terminal B",
        airportCode: "LGA",
        airlines: ["AA", "UA", "WN"],
        curbToSecurityMinutes: [5, 8],
        securityToGateMinutes: [6, 12],
        peakWindows: ["5:30am-9:00am", "4:00pm-7:00pm"],
        notes: ["Large central hall."],
        security: {
          waitEstimate: { offPeak: 15, normal: 22, peak: 35, holiday: 45 },
          services: { standard: true, precheck: true, clear: true },
          notes: [],
        },
      },
      {
        id: "C",
        name: "Terminal C",
        airportCode: "LGA",
        airlines: ["DL"],
        curbToSecurityMinutes: [5, 8],
        securityToGateMinutes: [5, 12],
        peakWindows: ["5:30am-8:30am", "4:00pm-7:00pm"],
        notes: ["Delta terminal."],
        security: {
          waitEstimate: { offPeak: 15, normal: 24, peak: 36, holiday: 46 },
          services: { standard: true, precheck: true, clear: true, "touchless-id": true },
          notes: [],
        },
      },
    ],
  },
  EWR: makeSimpleAirport("EWR", "Newark Liberty International Airport", "Newark", "NJ", "America/New_York", ["A", "B", "C"]),
  ATL: makeSimpleAirport("ATL", "Hartsfield-Jackson Atlanta International Airport", "Atlanta", "GA", "America/New_York", ["Domestic", "International"]),
  LAX: makeSimpleAirport("LAX", "Los Angeles International Airport", "Los Angeles", "CA", "America/Los_Angeles", ["1", "2", "3", "B", "4", "5", "6", "7", "8"]),
  ORD: makeSimpleAirport("ORD", "O'Hare International Airport", "Chicago", "IL", "America/Chicago", ["1", "2", "3", "5"]),
  DFW: makeSimpleAirport("DFW", "Dallas Fort Worth International Airport", "Dallas", "TX", "America/Chicago", ["A", "B", "C", "D", "E"]),
  DEN: makeSimpleAirport("DEN", "Denver International Airport", "Denver", "CO", "America/Denver", ["A", "B", "C"]),
  SFO: makeSimpleAirport("SFO", "San Francisco International Airport", "San Francisco", "CA", "America/Los_Angeles", ["1", "2", "3", "International"]),
  SEA: makeSimpleAirport("SEA", "Seattle-Tacoma International Airport", "Seattle", "WA", "America/Los_Angeles", ["Main", "North", "South"]),
  MIA: makeSimpleAirport("MIA", "Miami International Airport", "Miami", "FL", "America/New_York", ["North", "Central", "South"]),
  BOS: makeSimpleAirport("BOS", "Boston Logan International Airport", "Boston", "MA", "America/New_York", ["A", "B", "C", "E"]),
  CLT: makeSimpleAirport("CLT", "Charlotte Douglas International Airport", "Charlotte", "NC", "America/New_York", ["Main"]),
  IAH: makeSimpleAirport("IAH", "George Bush Intercontinental Airport", "Houston", "TX", "America/Chicago", ["A", "B", "C", "D", "E"]),
  IAD: makeSimpleAirport("IAD", "Washington Dulles International Airport", "Dulles", "VA", "America/New_York", ["Main", "A/B", "C/D"]),
  PHX: makeSimpleAirport("PHX", "Phoenix Sky Harbor International Airport", "Phoenix", "AZ", "America/Phoenix", ["3", "4"]),
  PHL: makeSimpleAirport("PHL", "Philadelphia International Airport", "Philadelphia", "PA", "America/New_York", ["A", "B", "C", "D", "E", "F"]),
  LAS: makeSimpleAirport("LAS", "Harry Reid International Airport", "Las Vegas", "NV", "America/Los_Angeles", ["1", "3"]),
  DCA: makeSimpleAirport("DCA", "Ronald Reagan Washington National Airport", "Washington", "DC", "America/New_York", ["1", "2"]),
  DTW: makeSimpleAirport("DTW", "Detroit Metropolitan Wayne County Airport", "Detroit", "MI", "America/New_York", ["McNamara", "North"]),
  MSP: makeSimpleAirport("MSP", "Minneapolis-Saint Paul International Airport", "Minneapolis", "MN", "America/Chicago", ["1", "2"]),
  SAN: makeSimpleAirport("SAN", "San Diego International Airport", "San Diego", "CA", "America/Los_Angeles", ["1", "2"]),
  AUS: makeSimpleAirport("AUS", "Austin-Bergstrom International Airport", "Austin", "TX", "America/Chicago", ["Barbara Jordan", "South"]),
  BNA: makeSimpleAirport("BNA", "Nashville International Airport", "Nashville", "TN", "America/Chicago", ["Main"]),
  MCO: makeSimpleAirport("MCO", "Orlando International Airport", "Orlando", "FL", "America/New_York", ["A", "B", "C"]),
  FLL: makeSimpleAirport("FLL", "Fort Lauderdale-Hollywood International Airport", "Fort Lauderdale", "FL", "America/New_York", ["1", "2", "3", "4"]),
  PDX: makeSimpleAirport("PDX", "Portland International Airport", "Portland", "OR", "America/Los_Angeles", ["Main"]),
};

export const airlineProfiles: AirlineProfile[] = [
  {
    code: "DL",
    name: "Delta Air Lines",
    airportAssignments: { JFK: "4", LGA: "C", ATL: "Domestic", LAX: "3", BOS: "A", SEA: "Main" },
    statusTiers: ["None", "Silver Medallion", "Gold Medallion", "Platinum Medallion", "Diamond Medallion / 360", "First Class"],
    alliance: "SkyTeam",
  },
  {
    code: "AA",
    name: "American Airlines",
    airportAssignments: { JFK: "8", LGA: "B", DFW: "C", MIA: "North", CLT: "Main", PHL: "B" },
    statusTiers: ["None", "AAdvantage Gold", "AAdvantage Platinum", "AAdvantage Platinum Pro", "AAdvantage Executive Platinum", "First Class"],
    alliance: "oneworld",
  },
  {
    code: "UA",
    name: "United Airlines",
    airportAssignments: { EWR: "C", LAX: "7", ORD: "1", DEN: "B", IAH: "C", SFO: "3" },
    statusTiers: ["None", "Premier Silver", "Premier Gold", "Premier Platinum", "Premier 1K", "First Class"],
    alliance: "Star Alliance",
  },
  {
    code: "B6",
    name: "JetBlue",
    airportAssignments: { JFK: "5", BOS: "C", LAX: "5", MCO: "A", FLL: "3" },
    statusTiers: ["None", "Mosaic 1", "Mosaic 2", "Mosaic 3", "Mosaic 4", "Mint"],
  },
  {
    code: "WN",
    name: "Southwest",
    airportAssignments: { LGA: "B", DEN: "C", LAS: "1", BNA: "Main", MCO: "A" },
    statusTiers: ["None", "A-List", "A-List Preferred", "Business Select"],
  },
  {
    code: "AS",
    name: "Alaska Airlines",
    airportAssignments: { JFK: "8", SEA: "North", LAX: "6", SFO: "2", SAN: "2" },
    statusTiers: ["None", "MVP", "MVP Gold", "MVP Gold 75K", "MVP Gold 100K", "First Class"],
  },
  {
    code: "NK",
    name: "Spirit Airlines",
    airportAssignments: { LGA: "A", MCO: "A", FLL: "4", LAS: "1" },
    statusTiers: ["None", "Saver$ Club", "Go Big"],
  },
];

function makeSimpleAirport(
  code: AirportProfile["code"],
  name: string,
  city: string,
  state: string,
  timezone: string,
  terminalIds: string[],
): AirportProfile {
  return {
    code,
    name,
    city,
    state,
    timezone,
    constructionBufferMinutes: { baseline: 5, peak: 12 },
    standardBoardingBuffer: { domestic: 30, international: 45 },
    defaultPostSecurityBuffer: 35,
    bagCutoffs: { checkedDomestic: 45, checkedInternational: 60, carryOnDomestic: 30, carryOnInternational: 45 },
    weatherStation: { lat: 0, lon: 0 },
    alerts: [],
    terminals: terminalIds.map((id) => ({
      id,
      name: `Terminal ${id}`,
      airportCode: code,
      airlines: [],
      curbToSecurityMinutes: [5, 8],
      securityToGateMinutes: [6, 12],
      peakWindows: ["5:30am-8:30am", "4:00pm-7:00pm"],
      notes: [],
      security: {
        waitEstimate: { offPeak: 15, normal: 22, peak: 35, holiday: 45 },
        services: { standard: true, precheck: true, clear: true },
        notes: [],
      },
    })),
  };
}
