import type { AirlineProfile, AirportProfile, PeakTravelWindow } from "@/types/airport";

export const peakTravelWindows: PeakTravelWindow[] = [
  {
    level: "extreme",
    multiplier: 1.5,
    name: "Thanksgiving return rush",
    dates: ["2026-11-25", "2026-11-29"],
  },
  {
    level: "extreme",
    multiplier: 1.5,
    name: "Christmas peak",
    dates: ["2026-12-18", "2026-12-19", "2026-12-20", "2026-12-21", "2026-12-26", "2026-12-27", "2026-12-28", "2026-12-29"],
  },
  {
    level: "high",
    multiplier: 1.35,
    name: "Holiday weekend pressure",
    dates: ["2026-05-22", "2026-05-25", "2026-07-02", "2026-07-05", "2026-09-04", "2026-09-07"],
  },
];

export const airportProfiles: Record<string, AirportProfile> = {
  JFK: {
    code: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    constructionBufferMinutes: { baseline: 15, peak: 30 },
    standardBoardingBuffer: { domestic: 30, international: 45 },
    defaultPostSecurityBuffer: 40,
    bagCutoffs: {
      checkedDomestic: 60,
      checkedInternational: 60,
      carryOnDomestic: 30,
      carryOnInternational: 60,
    },
    weatherStation: { lat: 40.6413, lon: -73.7781 },
    alerts: [
      "Major roadway construction through 2030 can add terminal access delay.",
      "Terminal 4 uses Van Wyck access; Terminal 8 uses JFK Expressway access.",
    ],
    terminals: [
      {
        id: "1",
        name: "Terminal 1",
        airportCode: "JFK",
        airlines: ["AF", "LH", "KE", "TK", "LX", "TP"],
        curbToSecurityMinutes: [5, 7],
        securityToGateMinutes: [5, 10],
        peakWindows: ["5:00am-8:00am", "6:00pm-10:00pm"],
        notes: ["Under major renovation.", "International banks can spike security fast."],
        security: {
          waitEstimate: { offPeak: 20, normal: 30, peak: 45, holiday: 60 },
          services: { standard: true, precheck: true },
          serviceHours: {
            precheck: { opensAt: "04:00", closesAt: "20:00" },
          },
          notes: ["No CLEAR."],
        },
      },
      {
        id: "4",
        name: "Terminal 4",
        airportCode: "JFK",
        airlines: ["DL", "KL", "VS", "LA", "AM", "EK", "EY", "SQ"],
        curbToSecurityMinutes: [7, 10],
        securityToGateMinutes: [5, 15],
        peakWindows: ["5:00am-8:00am", "4:00pm-7:00pm"],
        notes: ["Largest terminal.", "T4 RESERVE and Touchless ID can materially cut security time."],
        accessNotes: ["Use Van Wyck access.", "Remote rideshare pickup lot operates 12pm-2am."],
        security: {
          waitEstimate: { offPeak: 25, normal: 35, peak: 50, holiday: 65 },
          services: { standard: true, precheck: true, clear: true, reserve: true, "touchless-id": true },
          serviceHours: {
            precheck: { opensAt: "04:00", closesAt: "20:00" },
            clear: { opensAt: "04:30", closesAt: "22:00" },
            reserve: { opensAt: "04:00", closesAt: "22:00", note: "Bookable up to 72 hours before departure." },
            "touchless-id": { opensAt: "04:00", closesAt: "20:00" },
          },
          notes: ["Arrivals-level security can be shorter but lacks CLEAR."],
        },
      },
      {
        id: "5",
        name: "Terminal 5",
        airportCode: "JFK",
        airlines: ["B6"],
        curbToSecurityMinutes: [5, 5],
        securityToGateMinutes: [5, 10],
        peakWindows: ["6:00am-9:00am"],
        notes: ["Efficient, compact terminal."],
        accessNotes: ["Updated roadway pattern since October 2025."],
        security: {
          waitEstimate: { offPeak: 15, normal: 20, peak: 30, holiday: 45 },
          services: { standard: true, precheck: true },
          serviceHours: {
            precheck: { opensAt: "06:00", closesAt: "19:30", note: "Can close early." },
          },
          notes: ["No CLEAR."],
        },
      },
      {
        id: "7",
        name: "Terminal 7",
        airportCode: "JFK",
        airlines: ["EI", "AC", "FI", "F9", "ET", "LO", "DE", "NH"],
        curbToSecurityMinutes: [3, 5],
        securityToGateMinutes: [1, 2],
        peakWindows: ["5:00am-8:00am"],
        notes: ["Compact terminal.", "CLEAR kiosks present but currently closed."],
        accessNotes: ["Updated roadway pattern since October 2025."],
        security: {
          waitEstimate: { offPeak: 15, normal: 20, peak: 30, holiday: 40 },
          services: { standard: true, precheck: true },
          serviceHours: {
            precheck: { opensAt: "04:00", closesAt: "19:00" },
          },
          notes: ["CLEAR closed."],
        },
      },
      {
        id: "8",
        name: "Terminal 8",
        airportCode: "JFK",
        airlines: ["AA", "BA", "IB", "JL", "QF", "QR", "AS", "HA"],
        curbToSecurityMinutes: [5, 8],
        securityToGateMinutes: [5, 15],
        peakWindows: ["5:00am-8:00am", "4:00pm-7:00pm"],
        notes: ["Concourse C tunnel adds 10-15 minutes."],
        accessNotes: ["Use JFK Expressway access."],
        security: {
          waitEstimate: { offPeak: 20, normal: 30, peak: 45, holiday: 60 },
          services: { standard: true, precheck: true, "touchless-id": true },
          serviceHours: {
            precheck: { opensAt: "03:30", closesAt: "22:00" },
            "touchless-id": { opensAt: "04:00", closesAt: "20:00" },
          },
          notes: ["No CLEAR."],
        },
      },
    ],
  },
  LGA: {
    code: "LGA",
    name: "LaGuardia Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    constructionBufferMinutes: { baseline: 8, peak: 15 },
    standardBoardingBuffer: { domestic: 30, international: 40 },
    defaultPostSecurityBuffer: 35,
    bagCutoffs: { checkedDomestic: 45, checkedInternational: 60, carryOnDomestic: 30, carryOnInternational: 45 },
    weatherStation: { lat: 40.7769, lon: -73.8740 },
    alerts: ["Roadway congestion is common during weekday mornings."],
    terminals: [
      {
        id: "A",
        name: "Terminal A",
        airportCode: "LGA",
        airlines: ["F9", "NK", "B6"],
        curbToSecurityMinutes: [4, 6],
        securityToGateMinutes: [4, 8],
        peakWindows: ["6:00am-9:00am"],
        notes: ["Smaller footprint."],
        security: {
          waitEstimate: { offPeak: 12, normal: 20, peak: 30, holiday: 40 },
          services: { standard: true, precheck: true },
          notes: [],
        },
      },
      {
        id: "B",
        name: "Terminal B",
        airportCode: "LGA",
        airlines: ["AA", "UA", "WN"],
        curbToSecurityMinutes: [5, 8],
        securityToGateMinutes: [6, 12],
        peakWindows: ["5:30am-9:00am", "4:00pm-7:00pm"],
        notes: ["Large central hall."],
        security: {
          waitEstimate: { offPeak: 15, normal: 22, peak: 35, holiday: 45 },
          services: { standard: true, precheck: true, clear: true },
          notes: [],
        },
      },
      {
        id: "C",
        name: "Terminal C",
        airportCode: "LGA",
        airlines: ["DL"],
        curbToSecurityMinutes: [5, 8],
        securityToGateMinutes: [5, 12],
        peakWindows: ["5:30am-8:30am", "4:00pm-7:00pm"],
        notes: ["Delta terminal."],
        security: {
          waitEstimate: { offPeak: 15, normal: 24, peak: 36, holiday: 46 },
          services: { standard: true, precheck: true, clear: true, "touchless-id": true },
          notes: [],
        },
      },
    ],
  },
  EWR: makeSimpleAirport("EWR", "Newark Liberty International Airport", "Newark", "NJ", "America/New_York", ["A", "B", "C"], { lat: 40.6895, lon: -74.1745 }),
  ATL: makeSimpleAirport("ATL", "Hartsfield-Jackson Atlanta International Airport", "Atlanta", "GA", "America/New_York", ["Domestic", "International"], { lat: 33.6407, lon: -84.4277 }),
  LAX: makeSimpleAirport("LAX", "Los Angeles International Airport", "Los Angeles", "CA", "America/Los_Angeles", ["1", "2", "3", "B", "4", "5", "6", "7", "8"], { lat: 33.9416, lon: -118.4085 }),
  ORD: makeSimpleAirport("ORD", "O'Hare International Airport", "Chicago", "IL", "America/Chicago", ["1", "2", "3", "5"], { lat: 41.9742, lon: -87.9073 }),
  DFW: makeSimpleAirport("DFW", "Dallas Fort Worth International Airport", "Dallas", "TX", "America/Chicago", ["A", "B", "C", "D", "E"], { lat: 32.8998, lon: -97.0403 }),
  DEN: makeSimpleAirport("DEN", "Denver International Airport", "Denver", "CO", "America/Denver", ["A", "B", "C"], { lat: 39.8561, lon: -104.6737 }),
  SFO: makeSimpleAirport("SFO", "San Francisco International Airport", "San Francisco", "CA", "America/Los_Angeles", ["1", "2", "3", "International"], { lat: 37.6213, lon: -122.379 }),
  SEA: makeSimpleAirport("SEA", "Seattle-Tacoma International Airport", "Seattle", "WA", "America/Los_Angeles", ["Main", "North", "South"], { lat: 47.4502, lon: -122.3088 }),
  MIA: makeSimpleAirport("MIA", "Miami International Airport", "Miami", "FL", "America/New_York", ["North", "Central", "South"], { lat: 25.7959, lon: -80.287 }),
  BOS: makeSimpleAirport("BOS", "Boston Logan International Airport", "Boston", "MA", "America/New_York", ["A", "B", "C", "E"], { lat: 42.3656, lon: -71.0096 }),
  CLT: makeSimpleAirport("CLT", "Charlotte Douglas International Airport", "Charlotte", "NC", "America/New_York", ["Main"], { lat: 35.2144, lon: -80.9473 }),
  IAH: makeSimpleAirport("IAH", "George Bush Intercontinental Airport", "Houston", "TX", "America/Chicago", ["A", "B", "C", "D", "E"], { lat: 29.9902, lon: -95.3368 }),
  IAD: makeSimpleAirport("IAD", "Washington Dulles International Airport", "Dulles", "VA", "America/New_York", ["Main", "A/B", "C/D"], { lat: 38.9531, lon: -77.4565 }),
  PHX: makeSimpleAirport("PHX", "Phoenix Sky Harbor International Airport", "Phoenix", "AZ", "America/Phoenix", ["3", "4"], { lat: 33.4373, lon: -112.0078 }),
  PHL: makeSimpleAirport("PHL", "Philadelphia International Airport", "Philadelphia", "PA", "America/New_York", ["A", "B", "C", "D", "E", "F"], { lat: 39.8744, lon: -75.2424 }),
  LAS: makeSimpleAirport("LAS", "Harry Reid International Airport", "Las Vegas", "NV", "America/Los_Angeles", ["1", "3"], { lat: 36.084, lon: -115.1537 }),
  DCA: makeSimpleAirport("DCA", "Ronald Reagan Washington National Airport", "Washington", "DC", "America/New_York", ["1", "2"], { lat: 38.8512, lon: -77.0402 }),
  DTW: makeSimpleAirport("DTW", "Detroit Metropolitan Wayne County Airport", "Detroit", "MI", "America/New_York", ["McNamara", "North"], { lat: 42.2162, lon: -83.3554 }),
  MSP: makeSimpleAirport("MSP", "Minneapolis-Saint Paul International Airport", "Minneapolis", "MN", "America/Chicago", ["1", "2"], { lat: 44.8848, lon: -93.2223 }),
  SAN: makeSimpleAirport("SAN", "San Diego International Airport", "San Diego", "CA", "America/Los_Angeles", ["1", "2"], { lat: 32.7338, lon: -117.1933 }),
  AUS: makeSimpleAirport("AUS", "Austin-Bergstrom International Airport", "Austin", "TX", "America/Chicago", ["Barbara Jordan", "South"], { lat: 30.1975, lon: -97.6664 }),
  BNA: makeSimpleAirport("BNA", "Nashville International Airport", "Nashville", "TN", "America/Chicago", ["Main"], { lat: 36.1263, lon: -86.6774 }),
  MCO: makeSimpleAirport("MCO", "Orlando International Airport", "Orlando", "FL", "America/New_York", ["A", "B", "C"], { lat: 28.4312, lon: -81.3081 }),
  FLL: makeSimpleAirport("FLL", "Fort Lauderdale-Hollywood International Airport", "Fort Lauderdale", "FL", "America/New_York", ["1", "2", "3", "4"], { lat: 26.0742, lon: -80.1506 }),
  PDX: makeSimpleAirport("PDX", "Portland International Airport", "Portland", "OR", "America/Los_Angeles", ["Main"], { lat: 45.5898, lon: -122.5951 }),
  SLC: makeSimpleAirport("SLC", "Salt Lake City International Airport", "Salt Lake City", "UT", "America/Denver", ["A", "B"], { lat: 40.7899, lon: -111.9791 }),
  TPA: makeSimpleAirport("TPA", "Tampa International Airport", "Tampa", "FL", "America/New_York", ["A", "C", "E", "F"], { lat: 27.9772, lon: -82.5311 }),
  BWI: makeSimpleAirport("BWI", "Baltimore/Washington International Airport", "Baltimore", "MD", "America/New_York", ["A/B", "C", "D", "E"], { lat: 39.1774, lon: -76.6684 }),
  MDW: makeSimpleAirport("MDW", "Chicago Midway International Airport", "Chicago", "IL", "America/Chicago", ["Main"], { lat: 41.7868, lon: -87.7522 }),
  DAL: makeSimpleAirport("DAL", "Dallas Love Field", "Dallas", "TX", "America/Chicago", ["Main"], { lat: 32.8471, lon: -96.8517 }),
  HNL: makeSimpleAirport("HNL", "Daniel K. Inouye International Airport", "Honolulu", "HI", "Pacific/Honolulu", ["1", "2", "3"], { lat: 21.3245, lon: -157.925 }),
  RDU: makeSimpleAirport("RDU", "Raleigh-Durham International Airport", "Raleigh", "NC", "America/New_York", ["1", "2"], { lat: 35.8801, lon: -78.788 }),
  MSY: makeSimpleAirport("MSY", "Louis Armstrong New Orleans International Airport", "New Orleans", "LA", "America/Chicago", ["Main"], { lat: 29.9934, lon: -90.258 }),
  STL: makeSimpleAirport("STL", "St. Louis Lambert International Airport", "St. Louis", "MO", "America/Chicago", ["1", "2"], { lat: 38.7487, lon: -90.37 }),
  SJC: makeSimpleAirport("SJC", "San Jose Mineta International Airport", "San Jose", "CA", "America/Los_Angeles", ["A", "B"], { lat: 37.3639, lon: -121.9289 }),
  OAK: makeSimpleAirport("OAK", "Oakland International Airport", "Oakland", "CA", "America/Los_Angeles", ["1", "2"], { lat: 37.7126, lon: -122.2197 }),
  SMF: makeSimpleAirport("SMF", "Sacramento International Airport", "Sacramento", "CA", "America/Los_Angeles", ["A", "B"], { lat: 38.6954, lon: -121.5908 }),
  HOU: makeSimpleAirport("HOU", "William P. Hobby Airport", "Houston", "TX", "America/Chicago", ["Main"], { lat: 29.6454, lon: -95.2789 }),
  RSW: makeSimpleAirport("RSW", "Southwest Florida International Airport", "Fort Myers", "FL", "America/New_York", ["Main"], { lat: 26.5362, lon: -81.7552 }),
  SAT: makeSimpleAirport("SAT", "San Antonio International Airport", "San Antonio", "TX", "America/Chicago", ["A", "B"], { lat: 29.5312, lon: -98.4683 }),
  SJU: makeSimpleAirport("SJU", "Luis Muñoz Marín International Airport", "San Juan", "PR", "America/Puerto_Rico", ["A", "B", "C"], { lat: 18.4394, lon: -66.0018 }),
};

/** Synthesize a generic profile for an airport we haven't curated. */
export function makeGenericAirport(
  code: string,
  name?: string,
  timezone?: string,
  coord?: { lat: number; lon: number },
): AirportProfile {
  return makeSimpleAirport(
    code,
    name ?? `${code} Airport`,
    name ?? code,
    "",
    timezone ?? "America/New_York",
    ["Main"],
    coord ?? { lat: 0, lon: 0 },
  );
}

export const airlineProfiles: AirlineProfile[] = [
  {
    code: "DL",
    name: "Delta Air Lines",
    airportAssignments: { JFK: "4", LGA: "C", ATL: "Domestic", LAX: "3", BOS: "A", SEA: "Main" },
    statusTiers: ["None", "Silver Medallion", "Gold Medallion", "Platinum Medallion", "Diamond Medallion / 360", "First Class"],
    alliance: "SkyTeam",
  },
  {
    code: "AA",
    name: "American Airlines",
    airportAssignments: { JFK: "8", LGA: "B", DFW: "C", MIA: "North", CLT: "Main", PHL: "B" },
    statusTiers: ["None", "AAdvantage Gold", "AAdvantage Platinum", "AAdvantage Platinum Pro", "AAdvantage Executive Platinum", "First Class"],
    alliance: "oneworld",
  },
  {
    code: "UA",
    name: "United Airlines",
    airportAssignments: { EWR: "C", LAX: "7", ORD: "1", DEN: "B", IAH: "C", SFO: "3" },
    statusTiers: ["None", "Premier Silver", "Premier Gold", "Premier Platinum", "Premier 1K", "First Class"],
    alliance: "Star Alliance",
  },
  {
    code: "B6",
    name: "JetBlue",
    airportAssignments: { JFK: "5", BOS: "C", LAX: "5", MCO: "A", FLL: "3" },
    statusTiers: ["None", "Mosaic 1", "Mosaic 2", "Mosaic 3", "Mosaic 4", "Mint"],
  },
  {
    code: "WN",
    name: "Southwest",
    airportAssignments: { LGA: "B", DEN: "C", LAS: "1", BNA: "Main", MCO: "A" },
    statusTiers: ["None", "A-List", "A-List Preferred", "Business Select"],
  },
  {
    code: "AS",
    name: "Alaska Airlines",
    airportAssignments: { JFK: "8", SEA: "North", LAX: "6", SFO: "2", SAN: "2" },
    statusTiers: ["None", "MVP", "MVP Gold", "MVP Gold 75K", "MVP Gold 100K", "First Class"],
  },
  {
    code: "NK",
    name: "Spirit Airlines",
    airportAssignments: { LGA: "A", MCO: "A", FLL: "4", LAS: "1" },
    statusTiers: ["None", "Saver$ Club", "Go Big"],
  },
];

function makeSimpleAirport(
  code: AirportProfile["code"],
  name: string,
  city: string,
  state: string,
  timezone: string,
  terminalIds: string[],
  coord: { lat: number; lon: number },
): AirportProfile {
  return {
    code,
    name,
    city,
    state,
    timezone,
    constructionBufferMinutes: { baseline: 5, peak: 12 },
    standardBoardingBuffer: { domestic: 30, international: 45 },
    defaultPostSecurityBuffer: 35,
    bagCutoffs: { checkedDomestic: 45, checkedInternational: 60, carryOnDomestic: 30, carryOnInternational: 45 },
    weatherStation: coord,
    alerts: [],
    terminals: terminalIds.map((id) => ({
      id,
      name: `Terminal ${id}`,
      airportCode: code,
      airlines: [],
      curbToSecurityMinutes: [5, 8],
      securityToGateMinutes: [6, 12],
      peakWindows: ["5:30am-8:30am", "4:00pm-7:00pm"],
      notes: [],
      security: {
        waitEstimate: { offPeak: 15, normal: 22, peak: 35, holiday: 45 },
        services: { standard: true, precheck: true, clear: true },
        notes: [],
      },
    })),
  };
}
